-server
-Xms@{{ .Env.VM_OPTIONS_XMS }} -Xmx@{{ .Env.VM_OPTIONS_XMX }}
-XX:MaxMetaspaceSize=@{{ .Env.VM_OPTIONS_MAX_METASPACE_SIZE }}
-Dfile.encoding=@{{ .Env.JVM_FILE_ENCODING }}
-Dsun.net.inetaddr.ttl=@{{ .Env.JVM_TTL }}
-Duser.language=@{{ .Env.JVM_USER_LANGUAGE }}
-Duser.country=@{{ .Env.JVM_USER_COUNTRY }}
